---
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

#Packages:
library(stringr)
library(knitr)
```


```{r loadData}

#Load the data
rawData<-read.csv("Meeting 2/Meeting 2 Example Data.csv")

#Create a copy of the raw data
data<-rawData

```



```{r restructure}

###Rename Variables###

#Rename TIPI items
colnames(data)[6:15] <- paste0("tipi",
                               rep(c("Ex","Ag","Co","Ne","Op"), 2),
                               rep(1:2,each=5))


#Label which items are reverse coded
colnames(data)[c(7,11,13:15)]<-paste0(colnames(data)[c(7,11,13:15)],"r")


###Restructure Variables###

#Split condition variable into two columns
conditionSplit<-str_split_fixed(data$condition,"_",2)

#Name the newly created variables
colnames(conditionSplit)<-c("shockCause","moral")

#Add the split columns to the dataframe
data<-cbind(data,conditionSplit)

#Remove the original condition variable
data<-data[,-4]


###Recode Variables###

#Recode missing values in guilt to NAs
data$guilt<-ifelse(data$guilt==-99,NA,data$guilt)



#Make character variables numeric codes:
#0 = women; 1 = men
data$gender <- factor(data$gender,labels=c(1,0))

#0 = low, 1 = medium, 2 = high
data$shock <- factor(data$shock, labels=c(2,0,1))

#0 = partner, 1 = self
data$shockCause <- factor(data$shockCause, labels=c(0,1))

#0 = bad, 1 = good
data$moral <- factor(data$moral, labels=c(0,1))


###Reverse Code Variables###

#Reverse code relevant TIPI values
data[,c(6,10,12:14)] <- 8-data[,c(6,10,12:14)]

```



```{r compute}

#Compute personality variables
data$extra<-rowMeans(data[,c(5,10)])
data$agree<-rowMeans(data[,c(6,11)])
data$consc<-rowMeans(data[,c(7,12)])
data$neuro<-rowMeans(data[,c(8,13)])
data$open<-rowMeans(data[,c(9,14)])

```


# Codebook for Example Data

```{r codebook}

#Rearrange data
#Demographics first
#Predictors and then outcomes after
#Processed composites to the right of their components
data<-data[,c(1:3,5:14,20:24,4,18:19,15:17)]

#Create a codebook
codebook<-data.frame("variable"=colnames(data))

#Briefly describe each variable
codebook$description <- c(
  "Participant ID Number",
  "Gender of Participant (0 = Woman, 1 = Man)",
  "Age of Participant",
  "TIPI Extraversion 1",
  "TIPI Agreeableness 1 (R)",
  "TIPI Conscientiousness 1",
  "TIPI Neuroticism 1",
  "TIPI Openness 1",
  "TIPI Extraversion 2 (R)",
  "TIPI Agreeableness 2",
  "TIPI Conscientiousness 2 (R)",
  "TIPI Neuroticism 2 (R)",
  "TIPI Openness 2 (R)",
  "Composite Extraversion",
  "Composite Agreeableness",
  "Composite Conscientiousness",
  "Composite Neuroticism",
  "Composite Openness",
  "Shock Voltage (0 = low, 1 = medium, 2 = high)",
  "Shock Cause (0 = partner, 1 = self)",
  "Partner Morality (0 = bad, 1 = good)",
  "Pre-Shock Generosity ($ shared)",
  "Post-Shock Generosity ($ shared)",
  "Self-Reported Guilt after Shock"
  )

#Save the data type for each variable
codebook$type<-sapply(data,class)

#Output the codebook as a table
kable(codebook)

```



```{r save}

#Output the processed data file
write.csv(data,"Meeting 2/Meeting 2 Data PROCESSED.csv",row.names=F)

```

